import type { Session, VenueRoom, Speaker } from '@/types/agenda';

// ============================================
// VENUE ROOMS - Salles détaillées
// ============================================

export const demoVenueRooms: VenueRoom[] = [
  // Centre de Conférences Paris La Défense
  {
    id: 'room-1',
    venueId: 'venue-1',
    name: 'Auditorium Principal',
    capacity: 500,
    area: 450,
    setupTheater: 500,
    setupClassroom: 300,
    setupBanquet: 350,
    setupCocktail: 600,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 1,
    venue: {
      id: 'venue-1',
      name: 'Centre de Conférences Paris La Défense',
      city: 'Paris',
    },
  },
  {
    id: 'room-2',
    venueId: 'venue-1',
    name: 'Salle Atelier A',
    capacity: 80,
    area: 90,
    setupTheater: 80,
    setupClassroom: 50,
    setupBanquet: 60,
    setupCocktail: 100,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 2,
    venue: {
      id: 'venue-1',
      name: 'Centre de Conférences Paris La Défense',
      city: 'Paris',
    },
  },
  {
    id: 'room-3',
    venueId: 'venue-1',
    name: 'Salle Atelier B',
    capacity: 80,
    area: 90,
    setupTheater: 80,
    setupClassroom: 50,
    setupBanquet: 60,
    setupCocktail: 100,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 2,
    venue: {
      id: 'venue-1',
      name: 'Centre de Conférences Paris La Défense',
      city: 'Paris',
    },
  },
  {
    id: 'room-4',
    venueId: 'venue-1',
    name: 'Salle Networking',
    capacity: 150,
    area: 180,
    setupTheater: 120,
    setupClassroom: 80,
    setupBanquet: 100,
    setupCocktail: 200,
    hasProjector: false,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 1,
    venue: {
      id: 'venue-1',
      name: 'Centre de Conférences Paris La Défense',
      city: 'Paris',
    },
  },
  // Hôtel Royal Monceau
  {
    id: 'room-5',
    venueId: 'venue-2',
    name: 'Salon Royal',
    capacity: 200,
    area: 220,
    setupTheater: 200,
    setupClassroom: 120,
    setupBanquet: 150,
    setupCocktail: 250,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 0,
    venue: {
      id: 'venue-2',
      name: 'Hôtel Royal Monceau',
      city: 'Paris',
    },
  },
  {
    id: 'room-6',
    venueId: 'venue-2',
    name: 'Salon Monceau',
    capacity: 60,
    area: 65,
    setupTheater: 60,
    setupClassroom: 40,
    setupBanquet: 40,
    setupCocktail: 80,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 1,
    venue: {
      id: 'venue-2',
      name: 'Hôtel Royal Monceau',
      city: 'Paris',
    },
  },
];

// ============================================
// SESSIONS - Séminaire Tech 2024 (event-1)
// ============================================

export const demoSessions: Session[] = [
  // ===== JOUR 1 - 15 Juin 2024 =====
  {
    id: 'session-1',
    eventId: 'event-1',
    title: 'Accueil & Café de bienvenue',
    description: 'Enregistrement des participants et café de bienvenue',
    type: 'BREAK',
    startTime: new Date('2024-06-15T08:30:00'),
    endTime: new Date('2024-06-15T09:00:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: [],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-2',
    eventId: 'event-1',
    title: 'Session plénière d\'ouverture',
    description: 'Discours d\'ouverture et présentation des tendances technologiques 2024',
    type: 'PLENARY',
    startTime: new Date('2024-06-15T09:00:00'),
    endTime: new Date('2024-06-15T10:30:00'),
    venueRoomId: 'room-1',
    venueRoom: demoVenueRooms[0],
    maxCapacity: 500,
    isPublic: true,
    language: 'fr',
    tags: ['keynote', 'tendances', 'IA'],
    speakers: [
      {
        id: 'speaker-1',
        name: 'Sophie Martin',
        title: 'CEO',
        company: 'TechVision France',
        bio: 'Experte en transformation digitale avec 15 ans d\'expérience',
        photo: 'https://i.pravatar.cc/150?img=1',
        email: 'sophie.martin@techvision.fr',
        order: 0,
      },
      {
        id: 'speaker-2',
        name: 'Jean Dupont',
        title: 'CTO',
        company: 'InnovCorp',
        bio: 'Spécialiste IA et Machine Learning',
        photo: 'https://i.pravatar.cc/150?img=12',
        email: 'jean.dupont@innovcorp.com',
        order: 1,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 243,
      feedbacks: 187,
    },
  },
  {
    id: 'session-3',
    eventId: 'event-1',
    title: 'Pause café',
    type: 'BREAK',
    startTime: new Date('2024-06-15T10:30:00'),
    endTime: new Date('2024-06-15T11:00:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: [],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-4',
    eventId: 'event-1',
    title: 'Atelier: Intelligence Artificielle Générative',
    description: 'Découverte pratique des outils IA pour l\'entreprise: ChatGPT, Midjourney, GitHub Copilot',
    type: 'WORKSHOP',
    startTime: new Date('2024-06-15T11:00:00'),
    endTime: new Date('2024-06-15T12:30:00'),
    venueRoomId: 'room-2',
    venueRoom: demoVenueRooms[1],
    maxCapacity: 80,
    isPublic: true,
    language: 'fr',
    tags: ['IA', 'pratique', 'hands-on', 'ChatGPT'],
    speakers: [
      {
        id: 'speaker-3',
        name: 'Marie Lefevre',
        title: 'Data Scientist',
        company: 'AI Solutions',
        bio: 'Spécialiste en IA générative et NLP',
        photo: 'https://i.pravatar.cc/150?img=5',
        email: 'marie.lefevre@aisolutions.com',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 78,
      feedbacks: 65,
    },
  },
  {
    id: 'session-5',
    eventId: 'event-1',
    title: 'Atelier: Cybersécurité & Zero Trust',
    description: 'Stratégies de sécurité modernes pour protéger votre infrastructure',
    type: 'WORKSHOP',
    startTime: new Date('2024-06-15T11:00:00'),
    endTime: new Date('2024-06-15T12:30:00'),
    venueRoomId: 'room-3',
    venueRoom: demoVenueRooms[2],
    maxCapacity: 80,
    isPublic: true,
    language: 'fr',
    tags: ['sécurité', 'cyber', 'zero-trust'],
    speakers: [
      {
        id: 'speaker-4',
        name: 'Thomas Bernard',
        title: 'CISO',
        company: 'SecureNet',
        bio: '20 ans d\'expérience en cybersécurité',
        photo: 'https://i.pravatar.cc/150?img=13',
        email: 'thomas.bernard@securenet.fr',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 76,
      feedbacks: 58,
    },
  },
  {
    id: 'session-6',
    eventId: 'event-1',
    title: 'Déjeuner networking',
    description: 'Déjeuner buffet avec opportunités de networking',
    type: 'MEAL',
    startTime: new Date('2024-06-15T12:30:00'),
    endTime: new Date('2024-06-15T14:00:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: ['networking'],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-7',
    eventId: 'event-1',
    title: 'Cloud Native & Kubernetes',
    description: 'Architecture et best practices pour des applications cloud-native',
    type: 'WORKSHOP',
    startTime: new Date('2024-06-15T14:00:00'),
    endTime: new Date('2024-06-15T15:30:00'),
    venueRoomId: 'room-2',
    venueRoom: demoVenueRooms[1],
    maxCapacity: 80,
    isPublic: true,
    language: 'fr',
    tags: ['cloud', 'kubernetes', 'devops'],
    speakers: [
      {
        id: 'speaker-5',
        name: 'Lucas Petit',
        title: 'DevOps Architect',
        company: 'CloudMasters',
        bio: 'Expert Kubernetes et CNCF',
        photo: 'https://i.pravatar.cc/150?img=14',
        email: 'lucas.petit@cloudmasters.io',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 74,
      feedbacks: 61,
    },
  },
  {
    id: 'session-8',
    eventId: 'event-1',
    title: 'Web3 & Blockchain pour l\'entreprise',
    description: 'Cas d\'usage concrets de la blockchain dans le monde professionnel',
    type: 'WORKSHOP',
    startTime: new Date('2024-06-15T14:00:00'),
    endTime: new Date('2024-06-15T15:30:00'),
    venueRoomId: 'room-3',
    venueRoom: demoVenueRooms[2],
    maxCapacity: 80,
    isPublic: true,
    language: 'fr',
    tags: ['blockchain', 'web3', 'crypto'],
    speakers: [
      {
        id: 'speaker-6',
        name: 'Emma Rousseau',
        title: 'Blockchain Consultant',
        company: 'CryptoEnterprise',
        bio: 'Spécialiste blockchain et smart contracts',
        photo: 'https://i.pravatar.cc/150?img=9',
        email: 'emma.rousseau@cryptoent.com',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 68,
      feedbacks: 52,
    },
  },
  {
    id: 'session-9',
    eventId: 'event-1',
    title: 'Pause café',
    type: 'BREAK',
    startTime: new Date('2024-06-15T15:30:00'),
    endTime: new Date('2024-06-15T16:00:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: [],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-10',
    eventId: 'event-1',
    title: 'Table ronde: L\'avenir du travail hybride',
    description: 'Discussion avec des experts sur l\'évolution du travail post-COVID',
    type: 'PLENARY',
    startTime: new Date('2024-06-15T16:00:00'),
    endTime: new Date('2024-06-15T17:30:00'),
    venueRoomId: 'room-1',
    venueRoom: demoVenueRooms[0],
    maxCapacity: 500,
    isPublic: true,
    language: 'fr',
    tags: ['RH', 'futur du travail', 'hybride'],
    speakers: [
      {
        id: 'speaker-7',
        name: 'Claire Moreau',
        title: 'DRH',
        company: 'Global Tech Corp',
        bio: 'Experte en transformation RH',
        photo: 'https://i.pravatar.cc/150?img=10',
        email: 'claire.moreau@globaltech.com',
        order: 0,
      },
      {
        id: 'speaker-8',
        name: 'Alexandre Dubois',
        title: 'Consultant',
        company: 'Future of Work',
        bio: 'Consultant en organisation du travail',
        photo: 'https://i.pravatar.cc/150?img=15',
        email: 'alex.dubois@futureofwork.fr',
        order: 1,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 198,
      feedbacks: 145,
    },
  },
  {
    id: 'session-11',
    eventId: 'event-1',
    title: 'Cocktail de networking',
    description: 'Cocktail dinatoire et networking informel',
    type: 'NETWORKING',
    startTime: new Date('2024-06-15T18:00:00'),
    endTime: new Date('2024-06-15T20:00:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: ['networking', 'social'],
    speakers: [],
    status: 'PUBLISHED',
  },

  // ===== JOUR 2 - 16 Juin 2024 =====
  {
    id: 'session-12',
    eventId: 'event-1',
    title: 'Petit-déjeuner & Accueil Jour 2',
    type: 'MEAL',
    startTime: new Date('2024-06-16T08:30:00'),
    endTime: new Date('2024-06-16T09:00:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: [],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-13',
    eventId: 'event-1',
    title: 'Keynote: L\'IA au service de la durabilité',
    description: 'Comment l\'intelligence artificielle peut accélérer la transition écologique',
    type: 'PLENARY',
    startTime: new Date('2024-06-16T09:00:00'),
    endTime: new Date('2024-06-16T10:00:00'),
    venueRoomId: 'room-1',
    venueRoom: demoVenueRooms[0],
    maxCapacity: 500,
    isPublic: true,
    language: 'en',
    tags: ['IA', 'sustainability', 'green tech'],
    speakers: [
      {
        id: 'speaker-9',
        name: 'Dr. Sarah Johnson',
        title: 'Chief AI Officer',
        company: 'GreenAI',
        bio: 'Pioneer in sustainable AI solutions',
        photo: 'https://i.pravatar.cc/150?img=20',
        email: 'sarah.johnson@greenai.org',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 231,
      feedbacks: 176,
    },
  },
  {
    id: 'session-14',
    eventId: 'event-1',
    title: 'Pause café',
    type: 'BREAK',
    startTime: new Date('2024-06-16T10:00:00'),
    endTime: new Date('2024-06-16T10:30:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: [],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-15',
    eventId: 'event-1',
    title: 'Atelier: Design Thinking & Innovation',
    description: 'Méthodologie pratique pour innover et résoudre des problèmes complexes',
    type: 'WORKSHOP',
    startTime: new Date('2024-06-16T10:30:00'),
    endTime: new Date('2024-06-16T12:00:00'),
    venueRoomId: 'room-2',
    venueRoom: demoVenueRooms[1],
    maxCapacity: 80,
    isPublic: true,
    language: 'fr',
    tags: ['innovation', 'design thinking', 'créativité'],
    speakers: [
      {
        id: 'speaker-10',
        name: 'Pierre Laurent',
        title: 'Innovation Coach',
        company: 'InnoLab',
        bio: 'Coach certifié en design thinking',
        photo: 'https://i.pravatar.cc/150?img=17',
        email: 'pierre.laurent@innolab.fr',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 72,
      feedbacks: 68,
    },
  },
  {
    id: 'session-16',
    eventId: 'event-1',
    title: 'Atelier: Data Analytics avec Python',
    description: 'Introduction pratique à l\'analyse de données avec pandas et matplotlib',
    type: 'WORKSHOP',
    startTime: new Date('2024-06-16T10:30:00'),
    endTime: new Date('2024-06-16T12:00:00'),
    venueRoomId: 'room-3',
    venueRoom: demoVenueRooms[2],
    maxCapacity: 80,
    isPublic: true,
    language: 'fr',
    tags: ['data', 'python', 'analytics'],
    speakers: [
      {
        id: 'speaker-11',
        name: 'Julie Simon',
        title: 'Data Analyst',
        company: 'DataViz Pro',
        bio: 'Experte en visualisation de données',
        photo: 'https://i.pravatar.cc/150?img=22',
        email: 'julie.simon@datavizpro.com',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 79,
      feedbacks: 71,
    },
  },
  {
    id: 'session-17',
    eventId: 'event-1',
    title: 'Déjeuner & Networking',
    type: 'MEAL',
    startTime: new Date('2024-06-16T12:00:00'),
    endTime: new Date('2024-06-16T13:30:00'),
    venueRoomId: 'room-4',
    venueRoom: demoVenueRooms[3],
    isPublic: true,
    tags: ['networking'],
    speakers: [],
    status: 'PUBLISHED',
  },
  {
    id: 'session-18',
    eventId: 'event-1',
    title: 'Session plénière de clôture',
    description: 'Synthèse des deux jours, remise des prix et conclusion',
    type: 'PLENARY',
    startTime: new Date('2024-06-16T13:30:00'),
    endTime: new Date('2024-06-16T15:00:00'),
    venueRoomId: 'room-1',
    venueRoom: demoVenueRooms[0],
    maxCapacity: 500,
    isPublic: true,
    language: 'fr',
    tags: ['clôture', 'awards'],
    speakers: [
      {
        id: 'speaker-1',
        name: 'Sophie Martin',
        title: 'CEO',
        company: 'TechVision France',
        bio: 'Experte en transformation digitale avec 15 ans d\'expérience',
        photo: 'https://i.pravatar.cc/150?img=1',
        email: 'sophie.martin@techvision.fr',
        order: 0,
      },
    ],
    status: 'PUBLISHED',
    _count: {
      checkIns: 215,
      feedbacks: 189,
    },
  },
];

// ============================================
// PROGRAM TEMPLATES
// ============================================

export const demoProgramTemplates = [
  {
    id: 'template-1',
    name: 'Séminaire 2 jours - Tech Conference',
    description: 'Template pour conférence tech sur 2 jours avec ateliers parallèles',
    type: 'conference' as const,
    duration: 2,
    tags: ['tech', 'conférence', '2-jours'],
    isPublic: true,
    templateSessions: [
      {
        id: 'ts-1',
        title: 'Accueil & Café',
        type: 'BREAK' as const,
        dayOffset: 0,
        startTimeOfDay: '08:30',
        duration: 30,
        tags: [],
      },
      {
        id: 'ts-2',
        title: 'Keynote d\'ouverture',
        type: 'PLENARY' as const,
        dayOffset: 0,
        startTimeOfDay: '09:00',
        duration: 90,
        roomRequirements: { capacity: 300, hasProjector: true, hasSound: true },
        tags: ['keynote'],
      },
      {
        id: 'ts-3',
        title: 'Pause café',
        type: 'BREAK' as const,
        dayOffset: 0,
        startTimeOfDay: '10:30',
        duration: 30,
        tags: [],
      },
      {
        id: 'ts-4',
        title: 'Ateliers parallèles - Session 1',
        type: 'WORKSHOP' as const,
        dayOffset: 0,
        startTimeOfDay: '11:00',
        duration: 90,
        roomRequirements: { capacity: 50, hasProjector: true },
        tags: ['atelier'],
      },
      {
        id: 'ts-5',
        title: 'Déjeuner',
        type: 'MEAL' as const,
        dayOffset: 0,
        startTimeOfDay: '12:30',
        duration: 90,
        tags: [],
      },
    ],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
];
