// Mock data for demo mode

export const demoUser = {
  id: 'demo-user-1',
  email: 'demo@weevup.com',
  name: 'Démo Weevup',
  role: 'ADMIN',
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date('2024-01-15'),
};

export const demoEvents = [
  {
    id: 'event-1',
    name: 'Séminaire Tech 2024',
    description: 'Grand séminaire annuel sur les nouvelles technologies',
    startDate: new Date('2024-06-15T09:00:00'),
    endDate: new Date('2024-06-16T18:00:00'),
    status: 'PUBLISHED',
    languages: ['fr', 'en'],
    timezone: 'Europe/Paris',
    budgetTotal: 75000,
    createdById: 'demo-user-1',
    createdBy: {
      id: 'demo-user-1',
      name: 'Démo Weevup',
      email: 'demo@weevup.com',
    },
    _count: {
      participants: 245,
      sessions: 18,
      venues: 2,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'event-2',
    name: 'Convention Innovation 2024',
    description: 'Convention sur l\'innovation et le digital',
    startDate: new Date('2024-09-20T09:00:00'),
    endDate: new Date('2024-09-21T17:00:00'),
    status: 'DRAFT',
    languages: ['fr'],
    timezone: 'Europe/Paris',
    budgetTotal: 50000,
    createdById: 'demo-user-1',
    createdBy: {
      id: 'demo-user-1',
      name: 'Démo Weevup',
      email: 'demo@weevup.com',
    },
    _count: {
      participants: 0,
      sessions: 0,
      venues: 0,
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'event-3',
    name: 'Roadshow Paris 2024',
    description: 'Présentation itinérante de nos solutions',
    startDate: new Date('2024-05-10T14:00:00'),
    endDate: new Date('2024-05-10T19:00:00'),
    status: 'COMPLETED',
    languages: ['fr'],
    timezone: 'Europe/Paris',
    budgetTotal: 25000,
    createdById: 'demo-user-1',
    createdBy: {
      id: 'demo-user-1',
      name: 'Démo Weevup',
      email: 'demo@weevup.com',
    },
    _count: {
      participants: 156,
      sessions: 8,
      venues: 1,
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-05-11'),
  },
];

export const demoVenues = [
  {
    id: 'venue-1',
    name: 'Centre de Conférences Paris La Défense',
    description: 'Centre de conférences moderne au cœur de La Défense',
    type: 'CONFERENCE_CENTER',
    address: '1 Place de la Défense',
    city: 'Paris',
    country: 'France',
    postalCode: '92800',
    latitude: 48.8925,
    longitude: 2.2381,
    totalCapacity: 1500,
    priceRange: '€€€',
    rseScore: 92,
    contactName: 'Marie Dubois',
    contactEmail: 'contact@ccparis.fr',
    contactPhone: '+33 1 23 45 67 89',
    website: 'https://www.ccparis.fr',
    status: 'ACTIVE',
    rooms: [
      {
        id: 'room-1',
        name: 'Auditorium Principal',
        capacity: 800,
        area: 600,
        hasProjector: true,
        hasSound: true,
        hasWifi: true,
        hasAirCon: true,
        isAccessible: true,
      },
      {
        id: 'room-2',
        name: 'Salle Atelier A',
        capacity: 100,
        area: 80,
        hasProjector: true,
        hasSound: true,
        hasWifi: true,
        hasAirCon: true,
        isAccessible: true,
      },
    ],
    _count: {
      events: 5,
    },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'venue-2',
    name: 'Hôtel Royal Monceau',
    description: 'Hôtel de luxe avec espaces événementiels',
    type: 'HOTEL',
    address: '37 Avenue Hoche',
    city: 'Paris',
    country: 'France',
    postalCode: '75008',
    latitude: 48.8769,
    longitude: 2.2994,
    totalCapacity: 300,
    priceRange: '€€€€',
    rseScore: 78,
    contactName: 'Jean Martin',
    contactEmail: 'events@royalmonceau.com',
    contactPhone: '+33 1 42 99 88 00',
    website: 'https://www.leroyalmonceau.com',
    status: 'ACTIVE',
    rooms: [
      {
        id: 'room-3',
        name: 'Salon Haussmann',
        capacity: 150,
        area: 120,
        hasProjector: true,
        hasSound: true,
        hasWifi: true,
        hasAirCon: true,
        isAccessible: true,
      },
    ],
    _count: {
      events: 3,
    },
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'venue-3',
    name: 'Palais des Congrès de Lyon',
    description: 'Grand centre de congrès et d\'expositions',
    type: 'CONFERENCE_CENTER',
    address: '50 Quai Charles de Gaulle',
    city: 'Lyon',
    country: 'France',
    postalCode: '69006',
    latitude: 45.7640,
    longitude: 4.8357,
    totalCapacity: 3000,
    priceRange: '€€€',
    rseScore: 88,
    contactName: 'Sophie Lemoine',
    contactEmail: 'contact@palaiscongreslyon.com',
    contactPhone: '+33 4 72 82 26 26',
    website: 'https://www.palaiscongreslyon.com',
    status: 'ACTIVE',
    rooms: [
      {
        id: 'room-4',
        name: 'Amphithéâtre 3000',
        capacity: 3000,
        area: 2000,
        hasProjector: true,
        hasSound: true,
        hasWifi: true,
        hasAirCon: true,
        isAccessible: true,
      },
    ],
    _count: {
      events: 12,
    },
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
];

export const demoEventStats = {
  'event-1': {
    totalParticipants: 245,
    totalSessions: 18,
    totalCheckIns: 230,
    totalVenues: 2,
    participantsByStatus: [
      { status: 'REGISTERED', _count: 245 },
      { status: 'CHECKED_IN', _count: 230 },
      { status: 'NO_SHOW', _count: 15 },
    ],
    sessionsByType: [
      { type: 'PLENARY', _count: 4 },
      { type: 'WORKSHOP', _count: 10 },
      { type: 'BREAK', _count: 4 },
    ],
  },
  'event-2': {
    totalParticipants: 0,
    totalSessions: 0,
    totalCheckIns: 0,
    totalVenues: 0,
    participantsByStatus: [],
    sessionsByType: [],
  },
  'event-3': {
    totalParticipants: 156,
    totalSessions: 8,
    totalCheckIns: 152,
    totalVenues: 1,
    participantsByStatus: [
      { status: 'REGISTERED', _count: 156 },
      { status: 'CHECKED_IN', _count: 152 },
      { status: 'NO_SHOW', _count: 4 },
    ],
    sessionsByType: [
      { type: 'PLENARY', _count: 2 },
      { type: 'WORKSHOP', _count: 4 },
      { type: 'BREAK', _count: 2 },
    ],
  },
};

export const demoParticipant = {
  id: 'participant-1',
  eventId: 'event-1',
  email: 'jean.dupont@example.com',
  firstName: 'Jean',
  lastName: 'Dupont',
  company: 'TechCorp',
  jobTitle: 'Développeur Senior',
  phone: '+33 6 12 34 56 78',
  role: 'ATTENDEE',
  registeredAt: new Date('2024-02-15'),
  status: 'REGISTERED',
  qrCode: 'QR-DEMO-12345',
  language: 'fr',
  dietaryReqs: null,
  needsTransport: false,
  needsAccommodation: false,
  consentMarketing: true,
  consentData: true,
  consentDate: new Date('2024-02-15'),
  event: {
    id: 'event-1',
    name: 'Séminaire Tech 2024',
    startDate: new Date('2024-06-15'),
    endDate: new Date('2024-06-16'),
  },
};
