import type {
  Programme,
  Journee,
  Track,
  Segment,
  Session,
  VenueRoom,
  Contrainte,
  ProgrammeVersion,
  Publication,
} from '@/types/agenda';

// ============================================
// ÉVÉNEMENT 1: Grand Congrès Médical International 2024
// 3 jours, 8 tracks, 120+ sessions, multilingue
// ============================================

export const congressProgramme: Programme = {
  id: 'programme-congress-2024',
  evenementId: 'event-congress-2024',
  titre: 'Congrès Mondial de Médecine 2024',
  description: 'Le plus grand rassemblement de professionnels de santé en Europe',
  dateDebut: new Date('2024-10-15T08:00:00'),
  dateFin: new Date('2024-10-17T19:00:00'),
  etat: 'publie_client',
  version: '3.2.1',
  versionPrecedenteId: 'v3.2.0',
  languesSupportees: ['fr', 'en', 'es', 'de'],
  langueParDefaut: 'fr',
  tags: ['médecine', 'santé', 'recherche', 'innovation'],
  publications: {
    portail_web: true,
    portail_mobile: true,
    integration_calendrier: true,
    export_pdf: true,
  },
  createdAt: new Date('2024-01-15T10:00:00'),
  updatedAt: new Date('2024-10-01T16:45:00'),
  createdBy: 'dr.martin@congress2024.org',
  lastModifiedBy: 'admin@congress2024.org',
};

export const congressJournees: Journee[] = [
  {
    id: 'congress-j1',
    programmeId: 'programme-congress-2024',
    date: new Date('2024-10-15'),
    titre: 'Jour 1 - Innovation & Recherche',
    description: 'Ouverture du congrès et présentations des dernières avancées',
    ordre: 1,
    heuresOuverture: '08:00',
    heuresFermeture: '20:00',
    estActif: true,
    couleurTheme: '#DC2626', // Red medical
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'congress-j2',
    programmeId: 'programme-congress-2024',
    date: new Date('2024-10-16'),
    titre: 'Jour 2 - Pratiques Cliniques',
    description: 'Ateliers pratiques et retours d\'expérience',
    ordre: 2,
    heuresOuverture: '08:00',
    heuresFermeture: '19:30',
    estActif: true,
    couleurTheme: '#2563EB', // Blue
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'congress-j3',
    programmeId: 'programme-congress-2024',
    date: new Date('2024-10-17'),
    titre: 'Jour 3 - Futur de la Médecine',
    description: 'Prospective et technologies émergentes',
    ordre: 3,
    heuresOuverture: '08:30',
    heuresFermeture: '17:00',
    estActif: true,
    couleurTheme: '#059669', // Green
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-09-15'),
  },
];

export const congressTracks: Track[] = [
  {
    id: 'track-cardio',
    programmeId: 'programme-congress-2024',
    nom: 'Cardiologie',
    description: 'Maladies cardiovasculaires et innovations thérapeutiques',
    couleur: '#DC2626',
    ordre: 1,
    icon: '❤️',
    estActif: true,
    segmentsVisibles: ['seg-medecin', 'seg-chercheur', 'seg-vip'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-onco',
    programmeId: 'programme-congress-2024',
    nom: 'Oncologie',
    description: 'Cancérologie et traitements innovants',
    couleur: '#7C3AED',
    ordre: 2,
    icon: '🎗️',
    estActif: true,
    segmentsVisibles: ['seg-medecin', 'seg-chercheur', 'seg-vip'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-neuro',
    programmeId: 'programme-congress-2024',
    nom: 'Neurologie',
    description: 'Neurosciences et pathologies neurologiques',
    couleur: '#2563EB',
    ordre: 3,
    icon: '🧠',
    estActif: true,
    segmentsVisibles: ['seg-medecin', 'seg-chercheur', 'seg-vip'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-pediatrie',
    programmeId: 'programme-congress-2024',
    nom: 'Pédiatrie',
    description: 'Médecine de l\'enfant et de l\'adolescent',
    couleur: '#F59E0B',
    ordre: 4,
    icon: '👶',
    estActif: true,
    segmentsVisibles: ['seg-medecin', 'seg-infirmier', 'seg-vip'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-imaging',
    programmeId: 'programme-congress-2024',
    nom: 'Imagerie Médicale',
    description: 'Radiologie, IRM, scanner et nouvelles technologies',
    couleur: '#06B6D4',
    ordre: 5,
    icon: '📸',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-ai-health',
    programmeId: 'programme-congress-2024',
    nom: 'IA & Santé Numérique',
    description: 'Intelligence artificielle et transformation digitale',
    couleur: '#8B5CF6',
    ordre: 6,
    icon: '🤖',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-chirurgie',
    programmeId: 'programme-congress-2024',
    nom: 'Chirurgie',
    description: 'Techniques chirurgicales et robotique',
    couleur: '#10B981',
    ordre: 7,
    icon: '🔬',
    estActif: true,
    segmentsVisibles: ['seg-medecin', 'seg-vip'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'track-public-health',
    programmeId: 'programme-congress-2024',
    nom: 'Santé Publique',
    description: 'Épidémiologie, prévention et politique de santé',
    couleur: '#EC4899',
    ordre: 8,
    icon: '🌍',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
  },
];

export const congressSegments: Segment[] = [
  {
    id: 'seg-medecin',
    evenementId: 'event-congress-2024',
    nom: 'Médecins',
    description: 'Docteurs en médecine toutes spécialités',
    couleur: '#DC2626',
    type: 'role',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'seg-chercheur',
    evenementId: 'event-congress-2024',
    nom: 'Chercheurs',
    description: 'Chercheurs et scientifiques en biologie/médecine',
    couleur: '#7C3AED',
    type: 'role',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'seg-infirmier',
    evenementId: 'event-congress-2024',
    nom: 'Personnel Soignant',
    description: 'Infirmiers, aides-soignants, paramédicaux',
    couleur: '#2563EB',
    type: 'role',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'seg-vip',
    evenementId: 'event-congress-2024',
    nom: 'VIP',
    description: 'Accès premium - Professeurs, chefs de service',
    couleur: '#F59E0B',
    type: 'role',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'seg-industrie',
    evenementId: 'event-congress-2024',
    nom: 'Industrie Pharma',
    description: 'Représentants de l\'industrie pharmaceutique',
    couleur: '#10B981',
    type: 'role',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'seg-international',
    evenementId: 'event-congress-2024',
    nom: 'International',
    description: 'Participants non-francophones',
    couleur: '#06B6D4',
    type: 'langue',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

export const congressRooms: VenueRoom[] = [
  {
    id: 'congress-amphiA',
    venueId: 'venue-congress',
    name: 'Amphithéâtre Pasteur',
    capacity: 1200,
    area: 800,
    setupTheater: 1200,
    setupClassroom: 600,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 0,
    venue: {
      id: 'venue-congress',
      name: 'Palais des Congrès Paris',
      city: 'Paris',
    },
  },
  {
    id: 'congress-amphiB',
    venueId: 'venue-congress',
    name: 'Amphithéâtre Fleming',
    capacity: 800,
    area: 600,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 0,
  },
  {
    id: 'congress-salle1',
    venueId: 'venue-congress',
    name: 'Salle de Conférence 1',
    capacity: 300,
    area: 250,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 1,
  },
  {
    id: 'congress-salle2',
    venueId: 'venue-congress',
    name: 'Salle de Conférence 2',
    capacity: 300,
    area: 250,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 1,
  },
  {
    id: 'congress-salle3',
    venueId: 'venue-congress',
    name: 'Salle de Conférence 3',
    capacity: 300,
    area: 250,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 1,
  },
  {
    id: 'congress-workshop1',
    venueId: 'venue-congress',
    name: 'Atelier Pratique A',
    capacity: 50,
    area: 80,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 2,
  },
  {
    id: 'congress-workshop2',
    venueId: 'venue-congress',
    name: 'Atelier Pratique B',
    capacity: 50,
    area: 80,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 2,
  },
  {
    id: 'congress-workshop3',
    venueId: 'venue-congress',
    name: 'Atelier Pratique C',
    capacity: 50,
    area: 80,
    hasProjector: true,
    hasSound: true,
    hasWifi: true,
    hasAirCon: true,
    isAccessible: true,
    floor: 2,
  },
];

// Sessions complexes pour le congrès
export const congressSessions: Session[] = [
  // ==== JOUR 1 - Matin ====
  {
    id: 'cong-s001',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    title: 'Cérémonie d\'ouverture',
    description: 'Discours d\'ouverture du Président du Congrès et allocutions officielles',
    type: 'PLENARY',
    startTime: new Date('2024-10-15T08:30:00'),
    endTime: new Date('2024-10-15T09:30:00'),
    venueRoomId: 'congress-amphiA',
    maxCapacity: 1200,
    currentRegistrations: 1156,
    isPublic: true,
    language: 'fr',
    tags: ['ouverture', 'officiel'],
    speakers: [
      {
        id: 'spk-001',
        name: 'Prof. Jean-Pierre Dubois',
        title: 'Président du Congrès',
        company: 'CHU Paris',
        bio: 'Cardiologue renommé, 30 ans d\'expérience',
        photo: 'https://i.pravatar.cc/150?img=33',
        email: 'jp.dubois@chu-paris.fr',
        order: 0,
      },
    ],
    interactions: {
      qaActive: false,
      quizActive: false,
      sondageActive: false,
      wordcloudActive: false,
    },
    logistique: {
      ressources: ['Podium présidentiel', '4 micros', '2 écrans géants', 'Éclairage scénique', 'Drapeaux officiels'],
      tempsMontage: 120,
      tempsDemonte: 60,
      instructions: 'Prévoir traduction simultanée FR/EN/ES. Livestream pour participants à distance.',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 1143,
      feedbacks: 856,
      questions: 0,
    },
  },
  {
    id: 'cong-s002',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    trackId: 'track-cardio',
    title: 'Nouvelles approches en insuffisance cardiaque',
    description: 'État de l\'art sur les traitements de l\'insuffisance cardiaque chronique et aiguë',
    type: 'PLENARY',
    startTime: new Date('2024-10-15T09:45:00'),
    endTime: new Date('2024-10-15T11:15:00'),
    venueRoomId: 'congress-amphiA',
    maxCapacity: 1200,
    currentRegistrations: 987,
    isPublic: true,
    language: 'en',
    segmentsAutorises: ['seg-medecin', 'seg-chercheur', 'seg-vip'],
    tags: ['cardiologie', 'insuffisance cardiaque', 'recherche'],
    speakers: [
      {
        id: 'spk-002',
        name: 'Dr. Sarah Mitchell',
        title: 'Cardiologue',
        company: 'Mayo Clinic, USA',
        bio: 'Spécialiste mondiale de l\'insuffisance cardiaque',
        photo: 'https://i.pravatar.cc/150?img=45',
        email: 's.mitchell@mayo.edu',
        order: 0,
      },
      {
        id: 'spk-003',
        name: 'Prof. Marco Rossi',
        title: 'Chef de Service',
        company: 'Ospedale San Raffaele, Milano',
        bio: 'Expert en transplantation cardiaque',
        photo: 'https://i.pravatar.cc/150?img=12',
        email: 'm.rossi@sanraffaele.it',
        order: 1,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: false,
      sondageActive: true,
      wordcloudActive: false,
    },
    logistique: {
      ressources: ['2 micros HF', 'Écran 4K', 'Pointeur laser', 'Clicker présentation'],
      tempsMontage: 30,
      tempsDemonte: 15,
      instructions: 'Traduction simultanée EN→FR obligatoire',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 965,
      feedbacks: 743,
      questions: 47,
    },
  },
  {
    id: 'cong-s003',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    trackId: 'track-onco',
    title: 'Immunothérapie: Révolution en oncologie',
    description: 'Les dernières avancées en immunothérapie pour le traitement des cancers',
    type: 'WORKSHOP',
    startTime: new Date('2024-10-15T09:45:00'),
    endTime: new Date('2024-10-15T11:15:00'),
    venueRoomId: 'congress-salle1',
    maxCapacity: 300,
    currentRegistrations: 298,
    isPublic: true,
    inscriptionRequise: true,
    language: 'fr',
    segmentsAutorises: ['seg-medecin', 'seg-chercheur', 'seg-vip'],
    tags: ['oncologie', 'immunothérapie', 'innovation'],
    speakers: [
      {
        id: 'spk-004',
        name: 'Dr. Marie Lefort',
        title: 'Oncologue',
        company: 'Institut Gustave Roussy',
        bio: 'Pionnière de l\'immunothérapie en France',
        photo: 'https://i.pravatar.cc/150?img=23',
        email: 'm.lefort@gustaveroussy.fr',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: true,
      sondageActive: true,
      wordcloudActive: false,
    },
    logistique: {
      ressources: ['Micro HF', 'Vidéoprojecteur', 'Tableau blanc', 'Marqueurs'],
      tempsMontage: 20,
      tempsDemonte: 10,
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 295,
      feedbacks: 278,
      questions: 62,
    },
  },
  {
    id: 'cong-s004',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    trackId: 'track-neuro',
    title: 'Alzheimer: De la recherche à la clinique',
    description: 'Nouveaux biomarqueurs et perspectives thérapeutiques',
    type: 'WORKSHOP',
    startTime: new Date('2024-10-15T09:45:00'),
    endTime: new Date('2024-10-15T11:15:00'),
    venueRoomId: 'congress-salle2',
    maxCapacity: 300,
    currentRegistrations: 276,
    isPublic: true,
    inscriptionRequise: true,
    language: 'fr',
    segmentsAutorises: ['seg-medecin', 'seg-chercheur', 'seg-vip'],
    tags: ['neurologie', 'Alzheimer', 'recherche'],
    speakers: [
      {
        id: 'spk-005',
        name: 'Prof. Thomas Bernard',
        title: 'Neurologue',
        company: 'Hôpital de la Pitié-Salpêtrière',
        bio: 'Spécialiste des maladies neurodégénératives',
        photo: 'https://i.pravatar.cc/150?img=34',
        email: 't.bernard@psl.aphp.fr',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: false,
      sondageActive: true,
      wordcloudActive: true,
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 272,
      feedbacks: 245,
      questions: 38,
    },
  },
  {
    id: 'cong-s005',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    trackId: 'track-ai-health',
    title: 'IA en diagnostic médical',
    description: 'Applications de l\'intelligence artificielle pour le diagnostic assisté',
    type: 'WORKSHOP',
    startTime: new Date('2024-10-15T09:45:00'),
    endTime: new Date('2024-10-15T11:15:00'),
    venueRoomId: 'congress-salle3',
    maxCapacity: 300,
    currentRegistrations: 299,
    isPublic: true,
    inscriptionRequise: true,
    language: 'en',
    tags: ['IA', 'diagnostic', 'innovation'],
    speakers: [
      {
        id: 'spk-006',
        name: 'Dr. Kenji Tanaka',
        title: 'Data Scientist',
        company: 'Tokyo Medical University',
        bio: 'Expert en deep learning médical',
        photo: 'https://i.pravatar.cc/150?img=56',
        email: 'k.tanaka@tmu.ac.jp',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: true,
      sondageActive: false,
      wordcloudActive: true,
    },
    logistique: {
      ressources: ['50 laptops', 'WiFi renforcé', 'Serveur GPU', 'Dataset médical'],
      tempsMontage: 60,
      tempsDemonte: 30,
      instructions: 'Atelier hands-on - prévoir accès VPN sécurisé',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 297,
      feedbacks: 289,
      questions: 73,
    },
  },
  {
    id: 'cong-s006',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    title: 'Pause café & Networking',
    type: 'BREAK',
    startTime: new Date('2024-10-15T11:15:00'),
    endTime: new Date('2024-10-15T11:45:00'),
    isPublic: true,
    tags: ['pause', 'networking'],
    speakers: [],
    status: 'PUBLISHED',
  },
  // Session VIP exclusive
  {
    id: 'cong-s007',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    trackId: 'track-chirurgie',
    title: 'Masterclass VIP: Chirurgie Robotique Avancée',
    description: 'Techniques avancées de chirurgie assistée par robot - Réservé aux chirurgiens confirmés',
    type: 'WORKSHOP',
    startTime: new Date('2024-10-15T11:45:00'),
    endTime: new Date('2024-10-15T13:15:00'),
    venueRoomId: 'congress-workshop1',
    maxCapacity: 50,
    currentRegistrations: 48,
    isPublic: false,
    inscriptionRequise: true,
    accesPremium: true,
    language: 'fr',
    segmentsAutorises: ['seg-vip'],
    tags: ['chirurgie', 'robotique', 'VIP', 'masterclass'],
    speakers: [
      {
        id: 'spk-007',
        name: 'Prof. Laurent Dupuis',
        title: 'Chef de Service Chirurgie',
        company: 'CHU Lyon',
        bio: 'Pioneer en chirurgie robotique, 500+ interventions',
        photo: 'https://i.pravatar.cc/150?img=67',
        email: 'l.dupuis@chu-lyon.fr',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: false,
      sondageActive: false,
      wordcloudActive: false,
    },
    logistique: {
      ressources: ['Simulateur chirurgical Da Vinci', '3 écrans 4K', 'Kit d\'instruments', 'Caméra 3D'],
      tempsMontage: 90,
      tempsDemonte: 60,
      instructions: 'Salle stérile requise. Matériel très fragile - manipulation experts uniquement',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 47,
      feedbacks: 47,
      questions: 23,
    },
  },
  // Session avec prérequis
  {
    id: 'cong-s008',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    trackId: 'track-ai-health',
    title: 'IA Avancée: Deep Learning en Imagerie',
    description: 'Atelier avancé nécessitant les bases acquises lors de la session du matin',
    type: 'WORKSHOP',
    startTime: new Date('2024-10-15T14:30:00'),
    endTime: new Date('2024-10-15T16:00:00'),
    venueRoomId: 'congress-workshop2',
    maxCapacity: 50,
    currentRegistrations: 45,
    isPublic: true,
    inscriptionRequise: true,
    prerequis: ['cong-s005'], // Nécessite d'avoir assisté à la session IA du matin
    language: 'en',
    tags: ['IA', 'deep learning', 'avancé'],
    speakers: [
      {
        id: 'spk-006',
        name: 'Dr. Kenji Tanaka',
        title: 'Data Scientist',
        company: 'Tokyo Medical University',
        bio: 'Expert en deep learning médical',
        photo: 'https://i.pravatar.cc/150?img=56',
        email: 'k.tanaka@tmu.ac.jp',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: true,
      sondageActive: false,
      wordcloudActive: false,
    },
    logistique: {
      ressources: ['50 laptops avec GPU', 'WiFi dédié', 'Dataset IRM/Scanner 500GB', 'Jupyter Hub'],
      tempsMontage: 45,
      tempsDemonte: 30,
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 44,
      feedbacks: 43,
      questions: 56,
    },
  },
  {
    id: 'cong-s009',
    eventId: 'event-congress-2024',
    programmeId: 'programme-congress-2024',
    journeeId: 'congress-j1',
    title: 'Déjeuner Gala - Networking',
    description: 'Déjeuner buffet avec tables rondes thématiques',
    type: 'MEAL',
    startTime: new Date('2024-10-15T13:15:00'),
    endTime: new Date('2024-10-15T14:30:00'),
    isPublic: true,
    tags: ['déjeuner', 'networking', 'gala'],
    speakers: [],
    logistique: {
      ressources: ['Buffet 1200 personnes', '120 tables rondes', 'Service traiteur', 'Animation musicale'],
      tempsMontage: 180,
      tempsDemonte: 120,
    },
    status: 'PUBLISHED',
  },
];

// Contraintes du congrès
export const congressContraintes: Contrainte[] = [
  {
    id: 'ctr-001',
    programmeId: 'programme-congress-2024',
    nom: 'Pause minimale entre sessions',
    description: 'Minimum 15 minutes entre deux sessions dans la même salle',
    type: 'temps_pause',
    regle: {
      condition: 'IF session.venueRoomId === nextSession.venueRoomId',
      validation: 'THEN (nextSession.startTime - session.endTime) >= 15 minutes',
      message: 'Pause insuffisante entre sessions (minimum 15 min pour nettoyage et installation)',
    },
    severite: 'warning',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'ctr-002',
    programmeId: 'programme-congress-2024',
    nom: 'Capacité maximale avec marge',
    description: 'Ne pas dépasser 95% de la capacité pour raisons de sécurité',
    type: 'capacite_max',
    regle: {
      condition: 'IF session.currentRegistrations > 0',
      validation: 'THEN session.currentRegistrations <= (session.maxCapacity * 0.95)',
      message: 'Capacité dépassée - risque de sécurité (max 95% de la capacité)',
    },
    severite: 'error',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'ctr-003',
    programmeId: 'programme-congress-2024',
    nom: 'Couvre-feu salle',
    description: 'Aucune session après 20h pour respecter le règlement',
    type: 'heure_limite',
    regle: {
      condition: 'IF session.venueRoomId',
      validation: 'THEN session.endTime <= 20:00',
      message: 'Session termine après 20h - violation du règlement du palais',
    },
    severite: 'error',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'ctr-004',
    programmeId: 'programme-congress-2024',
    nom: 'Temps montage/démontage',
    description: 'Respecter les temps de montage et démontage logistique',
    type: 'montage_demontage',
    regle: {
      condition: 'IF session.logistique.tempsMontage > 0',
      validation: 'THEN firstSessionOfDay.startTime >= (journee.heuresOuverture + session.logistique.tempsMontage)',
      message: 'Temps de montage insuffisant avant la première session',
    },
    severite: 'warning',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'ctr-005',
    programmeId: 'programme-congress-2024',
    nom: 'Sessions VIP exclusives',
    description: 'Les sessions VIP ne peuvent pas se chevaucher',
    type: 'custom',
    regle: {
      condition: 'IF session.accesPremium === true',
      validation: 'THEN no overlap with other VIP sessions',
      message: 'Conflit de sessions VIP - les participants premium ne peuvent pas être à deux endroits',
    },
    severite: 'error',
    estActif: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

// Versioning
export const congressVersions: ProgrammeVersion[] = [
  {
    id: 'v3.2.0',
    programmeId: 'programme-congress-2024',
    version: '3.2.0',
    snapshot: {
      sessions: [], // Simplified - would contain full session list
      tracks: congressTracks,
      journees: congressJournees,
    },
    changelog: 'Ajout de 12 nouvelles sessions IA, modification horaires jour 2',
    etat: 'publie_interne',
    datePublication: new Date('2024-09-15T10:00:00'),
    createdBy: 'admin@congress2024.org',
    createdAt: new Date('2024-09-15T10:00:00'),
  },
  {
    id: 'v3.2.1',
    programmeId: 'programme-congress-2024',
    version: '3.2.1',
    snapshot: {
      sessions: congressSessions,
      tracks: congressTracks,
      journees: congressJournees,
    },
    changelog: 'Correction conflit salle workshop B, ajout traduction simultanée sessions internationales',
    etat: 'publie_client',
    datePublication: new Date('2024-10-01T16:45:00'),
    createdBy: 'admin@congress2024.org',
    createdAt: new Date('2024-10-01T16:45:00'),
  },
];

// Publications
export const congressPublications: Publication[] = [
  {
    id: 'pub-001',
    programmeId: 'programme-congress-2024',
    versionId: 'v3.2.1',
    canaux: {
      portail_web: true,
      portail_mobile: true,
      integration_calendrier: true,
      export_pdf: true,
    },
    segmentsCibles: ['seg-medecin', 'seg-chercheur', 'seg-infirmier'], // Tous sauf industrie
    dateDebutPublication: new Date('2024-10-01T17:00:00'),
    statut: 'active',
    notifierParticipants: true,
    messageNotification: 'Le programme définitif du Congrès Mondial de Médecine 2024 est disponible !',
    createdAt: new Date('2024-10-01T16:50:00'),
    updatedAt: new Date('2024-10-01T17:00:00'),
  },
  {
    id: 'pub-002',
    programmeId: 'programme-congress-2024',
    versionId: 'v3.2.1',
    canaux: {
      portail_web: true,
      portail_mobile: false,
      integration_calendrier: false,
      export_pdf: true,
    },
    segmentsCibles: ['seg-vip'],
    dateDebutPublication: new Date('2024-09-20T09:00:00'),
    statut: 'active',
    notifierParticipants: true,
    messageNotification: 'Accès prioritaire VIP: consultez le programme et réservez vos masterclass exclusives',
    createdAt: new Date('2024-09-20T08:55:00'),
  },
];

// ============================================
// ÉVÉNEMENT 2: TechConnect Summit 2024
// Convention B2B multi-formats avec roadshow
// ============================================

export const techConnectProgramme: Programme = {
  id: 'programme-techconnect-2024',
  evenementId: 'event-techconnect-2024',
  titre: 'TechConnect Summit 2024',
  description: 'La convention B2B de référence pour les décideurs tech',
  dateDebut: new Date('2024-11-20T09:00:00'),
  dateFin: new Date('2024-11-22T18:00:00'),
  etat: 'a_valider',
  version: '1.5.0-beta',
  languesSupportees: ['fr', 'en'],
  langueParDefaut: 'fr',
  tags: ['B2B', 'tech', 'networking', 'business'],
  publications: {
    portail_web: true,
    portail_mobile: true,
    integration_calendrier: true,
    export_pdf: true,
  },
  createdAt: new Date('2024-06-01T10:00:00'),
  updatedAt: new Date('2024-10-28T14:20:00'),
  createdBy: 'events@techconnect.io',
  lastModifiedBy: 'organizer@techconnect.io',
};

export const techConnectJournees: Journee[] = [
  {
    id: 'tc-j1',
    programmeId: 'programme-techconnect-2024',
    date: new Date('2024-11-20'),
    titre: 'Jour 1 - Keynotes & Expo',
    description: 'Conférences plénières et salon d\'exposition',
    ordre: 1,
    heuresOuverture: '09:00',
    heuresFermeture: '19:00',
    estActif: true,
    couleurTheme: '#3B82F6',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'tc-j2',
    programmeId: 'programme-techconnect-2024',
    date: new Date('2024-11-21'),
    titre: 'Jour 2 - Workshops & Matchmaking',
    description: 'Ateliers pratiques et rendez-vous B2B',
    ordre: 2,
    heuresOuverture: '09:00',
    heuresFermeture: '20:00',
    estActif: true,
    couleurTheme: '#10B981',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'tc-j3',
    programmeId: 'programme-techconnect-2024',
    date: new Date('2024-11-22'),
    titre: 'Jour 3 - Pitchs & Awards',
    description: 'Compétition startups et remise des prix',
    ordre: 3,
    heuresOuverture: '10:00',
    heuresFermeture: '18:00',
    estActif: true,
    couleurTheme: '#F59E0B',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-15'),
  },
];

export const techConnectTracks: Track[] = [
  {
    id: 'tc-track-saas',
    programmeId: 'programme-techconnect-2024',
    nom: 'SaaS & Cloud',
    description: 'Solutions cloud et software as a service',
    couleur: '#3B82F6',
    ordre: 1,
    icon: '☁️',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-track-fintech',
    programmeId: 'programme-techconnect-2024',
    nom: 'FinTech',
    description: 'Technologies financières et paiements',
    couleur: '#10B981',
    ordre: 2,
    icon: '💰',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-track-cybersec',
    programmeId: 'programme-techconnect-2024',
    nom: 'Cybersécurité',
    description: 'Sécurité informatique et protection des données',
    couleur: '#DC2626',
    ordre: 3,
    icon: '🔒',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-track-ai',
    programmeId: 'programme-techconnect-2024',
    nom: 'IA & Data',
    description: 'Intelligence artificielle et data science',
    couleur: '#8B5CF6',
    ordre: 4,
    icon: '🤖',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
];

export const techConnectSegments: Segment[] = [
  {
    id: 'tc-seg-ceo',
    evenementId: 'event-techconnect-2024',
    nom: 'C-Level',
    description: 'CEO, CTO, CFO et autres dirigeants',
    couleur: '#F59E0B',
    type: 'role',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-seg-investor',
    evenementId: 'event-techconnect-2024',
    nom: 'Investisseurs',
    description: 'VCs, Business Angels, Family Offices',
    couleur: '#10B981',
    type: 'role',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-seg-startup',
    evenementId: 'event-techconnect-2024',
    nom: 'Startups',
    description: 'Fondateurs et équipes de startups',
    couleur: '#3B82F6',
    type: 'role',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-seg-corporate',
    evenementId: 'event-techconnect-2024',
    nom: 'Entreprises',
    description: 'Grandes entreprises et ETI',
    couleur: '#8B5CF6',
    type: 'role',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
];

// Sessions avec logistique complexe
export const techConnectSessions: Session[] = [
  {
    id: 'tc-s001',
    eventId: 'event-techconnect-2024',
    programmeId: 'programme-techconnect-2024',
    journeeId: 'tc-j1',
    title: 'Setup & Installation Expo',
    description: 'Installation des stands exposants - équipes techniques uniquement',
    type: 'OTHER',
    startTime: new Date('2024-11-20T06:00:00'),
    endTime: new Date('2024-11-20T09:00:00'),
    maxCapacity: 50,
    currentRegistrations: 42,
    isPublic: false,
    segmentsExclus: ['tc-seg-ceo', 'tc-seg-investor', 'tc-seg-startup', 'tc-seg-corporate'],
    language: 'fr',
    tags: ['logistique', 'setup', 'technique'],
    speakers: [],
    logistique: {
      ressources: [
        '20 chariots élévateurs',
        '150 caisses de matériel',
        '50 km de câbles électriques',
        '200 projecteurs LED',
        'Équipe technique 30 personnes',
      ],
      tempsMontage: 0,
      tempsDemonte: 240, // 4h après pour démontage
      instructions:
        'CRITIQUE: Fenêtre de 3h pour installer 50 stands. Coordination avec chef de projet expo. Accès camions par quai de chargement est uniquement.',
    },
    status: 'PUBLISHED',
  },
  {
    id: 'tc-s002',
    eventId: 'event-techconnect-2024',
    programmeId: 'programme-techconnect-2024',
    journeeId: 'tc-j1',
    trackId: 'tc-track-saas',
    title: 'Keynote d\'ouverture: L\'avenir du SaaS en Europe',
    description: 'Vision stratégique et tendances 2025 par les leaders européens du SaaS',
    type: 'PLENARY',
    startTime: new Date('2024-11-20T09:30:00'),
    endTime: new Date('2024-11-20T10:45:00'),
    maxCapacity: 2000,
    currentRegistrations: 1847,
    isPublic: true,
    language: 'en',
    tags: ['keynote', 'SaaS', 'stratégie'],
    speakers: [
      {
        id: 'tc-spk-001',
        name: 'Mathilde Collin',
        title: 'CEO',
        company: 'Front',
        bio: 'Fondatrice de Front, SaaS valorisé à $1.7B',
        photo: 'https://i.pravatar.cc/150?img=44',
        email: 'm.collin@front.com',
        order: 0,
      },
      {
        id: 'tc-spk-002',
        name: 'Jonathan Anguelov',
        title: 'Co-founder',
        company: 'Aircall',
        bio: 'Co-fondateur d\'Aircall, licorne française',
        photo: 'https://i.pravatar.cc/150?img=52',
        email: 'j.anguelov@aircall.io',
        order: 1,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: false,
      sondageActive: true,
      wordcloudActive: true,
    },
    logistique: {
      ressources: [
        'Scène principale 15m x 8m',
        '4 micros HF',
        '2 écrans LED géants 10m x 5m',
        'Régie son/lumière complète',
        'Livestream 4K',
        'Traduction simultanée EN/FR',
      ],
      tempsMontage: 120,
      tempsDemonte: 60,
      instructions: 'VIP green room nécessaire. Répétition technique à 8h30.',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 1823,
      feedbacks: 1456,
      questions: 89,
    },
  },
  {
    id: 'tc-s003',
    eventId: 'event-techconnect-2024',
    programmeId: 'programme-techconnect-2024',
    journeeId: 'tc-j2',
    trackId: 'tc-track-fintech',
    title: 'Workshop: Construire une FinTech compliant',
    description: 'Réglementation, licences et conformité ACPR/AMF - Session avec cas pratiques',
    type: 'WORKSHOP',
    startTime: new Date('2024-11-21T10:00:00'),
    endTime: new Date('2024-11-21T12:30:00'),
    maxCapacity: 80,
    currentRegistrations: 79,
    isPublic: true,
    inscriptionRequise: true,
    accesPremium: false,
    language: 'fr',
    segmentsAutorises: ['tc-seg-ceo', 'tc-seg-startup'],
    tags: ['fintech', 'régulation', 'compliance', 'pratique'],
    speakers: [
      {
        id: 'tc-spk-003',
        name: 'Claire Chabas',
        title: 'Partner',
        company: 'Goodwin Procter',
        bio: 'Avocate spécialisée fintech et crypto',
        photo: 'https://i.pravatar.cc/150?img=25',
        email: 'c.chabas@goodwinlaw.com',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: true,
      sondageActive: true,
      wordcloudActive: false,
    },
    logistique: {
      ressources: ['80 tablettes avec cas pratiques', 'Documentation réglementaire', 'WiFi dédié', 'Paperboard'],
      tempsMontage: 30,
      tempsDemonte: 15,
      instructions: 'Documents confidentiels - signature NDA requise à l\'entrée',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 77,
      feedbacks: 74,
      questions: 124,
    },
  },
  {
    id: 'tc-s004',
    eventId: 'event-techconnect-2024',
    programmeId: 'programme-techconnect-2024',
    journeeId: 'tc-j2',
    title: 'Speed Networking Investisseurs-Startups',
    description: '20 minutes par rendez-vous - Format matchmaking B2B',
    type: 'NETWORKING',
    startTime: new Date('2024-11-21T14:00:00'),
    endTime: new Date('2024-11-21T17:00:00'),
    maxCapacity: 200,
    currentRegistrations: 186,
    isPublic: true,
    inscriptionRequise: true,
    language: 'fr',
    segmentsAutorises: ['tc-seg-investor', 'tc-seg-startup'],
    tags: ['networking', 'matchmaking', 'investissement'],
    speakers: [],
    interactions: {
      qaActive: false,
      quizActive: false,
      sondageActive: true,
      wordcloudActive: false,
    },
    logistique: {
      ressources: [
        '100 tables rondes 4 personnes',
        'Système de rotation automatisé',
        'Badges QR code pour scan',
        'App mobile matchmaking',
        'Chronomètre géant',
      ],
      tempsMontage: 90,
      tempsDemonte: 60,
      instructions:
        'Configuration complexe: tables numérotées avec QR codes. Timer automatique toutes les 20min. Prévoir personnel pour gérer le flux.',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 183,
      feedbacks: 167,
      questions: 0,
    },
  },
  {
    id: 'tc-s005',
    eventId: 'event-techconnect-2024',
    programmeId: 'programme-techconnect-2024',
    journeeId: 'tc-j3',
    title: 'Startup Pitch Competition - Finale',
    description: '10 startups finalistes - 7 minutes de pitch + 3 min Q&A - Prix: 100k€',
    type: 'PLENARY',
    startTime: new Date('2024-11-22T14:00:00'),
    endTime: new Date('2024-11-22T17:00:00'),
    maxCapacity: 1500,
    currentRegistrations: 1432,
    isPublic: true,
    language: 'en',
    tags: ['startup', 'pitch', 'competition', 'awards'],
    speakers: [
      {
        id: 'tc-spk-004',
        name: 'Roxanne Varza',
        title: 'Director',
        company: 'Station F',
        bio: 'Directrice de Station F',
        photo: 'https://i.pravatar.cc/150?img=31',
        email: 'r.varza@stationf.co',
        order: 0,
      },
    ],
    interactions: {
      qaActive: true,
      quizActive: false,
      sondageActive: true,
      wordcloudActive: true,
    },
    logistique: {
      ressources: [
        'Scène avec décor startup',
        'Système de vote en direct',
        '10 pitchs deck pré-chargés',
        'Timer visible 7min',
        'Caméras multi-angles',
        'Régie vidéo',
      ],
      tempsMontage: 90,
      tempsDemonte: 45,
      instructions: 'Timing STRICT: 7min pitch + 3min Q&A. Répétitions avec chaque startup à 13h.',
    },
    status: 'PUBLISHED',
    _count: {
      checkIns: 1398,
      feedbacks: 1245,
      questions: 156,
    },
  },
];

// Contraintes spécifiques à l'événement tech
export const techConnectContraintes: Contrainte[] = [
  {
    id: 'tc-ctr-001',
    programmeId: 'programme-techconnect-2024',
    nom: 'Networking sans chevauchement',
    description: 'Les sessions de networking ne doivent pas se chevaucher',
    type: 'custom',
    regle: {
      condition: 'IF session.type === "NETWORKING"',
      validation: 'THEN no overlap with other NETWORKING sessions',
      message: 'Les participants doivent pouvoir assister à toutes les sessions networking',
    },
    severite: 'error',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-ctr-002',
    programmeId: 'programme-techconnect-2024',
    nom: 'Matchmaking requiert inscription',
    description: 'Les sessions matchmaking nécessitent une inscription préalable',
    type: 'custom',
    regle: {
      condition: 'IF session.tags includes "matchmaking"',
      validation: 'THEN session.inscriptionRequise === true',
      message: 'Les sessions matchmaking nécessitent inscription pour gérer les binômes',
    },
    severite: 'error',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tc-ctr-003',
    programmeId: 'programme-techconnect-2024',
    nom: 'Setup avant ouverture',
    description: 'Le setup doit se terminer 30min avant la première session publique',
    type: 'montage_demontage',
    regle: {
      condition: 'IF session.type === "OTHER" AND session.tags includes "setup"',
      validation: 'THEN (firstPublicSession.startTime - session.endTime) >= 30 minutes',
      message: 'Pas assez de temps entre fin setup et début événement',
    },
    severite: 'error',
    estActif: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
];
